### ISSUE TITLE
linuxserver transmission docker & index.html

### ISSUE THREAD

**Issue by esticle** [6c65726f79/Transmissionic#1378]
**Describe the bug**

Hi, I'm trying out the skin on the [linuxserver docker image](https://hub.docker.com/r/linuxserver/transmission) (v4) and I keep on getting the message that index.html is not found.

This rings true as I have not found a index.html in the releases files - so what am I missing?

**To Reproduce**

Compose file:

```
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1006
      - PGID=1006
      - TZ=Europe/Paris
      - TRANSMISSION_WEB_HOME=/webui
    volumes:
      - /docker/transmission/transmissionic:/webui
      - /docker/transmission/config:/config
      - /docker/transmission/downloads:/downloads
      - /docker/transmission/watch:/watch

```

My /docker/transmission/transmissionic as per above contains the latest version extracted (note, no index.html):

```
$ ls /docker/transmission/transmissionic
android                electron           LICENSE            PRIVACY.md  resources  tsconfig.json
babel.config.js        ionic.config.json  package.json       public      scripts    vue.config.js
capacitor.config.json  ios                package-lock.json  README.md   src

```
And then when trying to browse it I get:

```
$ curl http://192.168.1.111:9091/transmission/web/ 
<h1>404: Not Found</h1>/webui/index.html (No such file or directory)
```
Any ideas what I'm doing wrong? 

**Platform:**
 - OS: Ubuntu 22.04 && docker linuxserver image latest (v4)
